name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm i

      - name: Generate
        run: npm run generate

      - name: Deploy
        run: |
          git config user.name "fabriciozeferino" && git config user.email "fabriciozeferino@gmail.com"
          npm run deploy
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   run: gh-pages -d dist
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
